//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cleanerAtt
    {
        public int cleanerAtt_id { get; set; }
        public string floor_id { get; set; }
        public System.DateTime cleaner_date { get; set; }
    
        public virtual floor floor { get; set; }
    }
}
