//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class finance
    {
        public int finance_id { get; set; }
        public string floor_id { get; set; }
        public double finance_transaction { get; set; }
        public string finance_desc { get; set; }
        public string finance_pMethod { get; set; }
        public string finance_type { get; set; }
        public System.DateTime finance_date { get; set; }
        public string finance_receipt { get; set; }
        public int user_id { get; set; }
    
        public virtual floor floor { get; set; }
        public virtual user user { get; set; }
    }
}
