//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profit
    {
        public int profit_id { get; set; }
        public int Investor_id { get; set; }
        public System.DateTime profit_month { get; set; }
        public string profit_value { get; set; }
    
        public virtual Investor Investor { get; set; }
    }
}
