//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reminds
    {
        public int reminder_id { get; set; }
        public Nullable<int> landlord_id { get; set; }
        public Nullable<int> tenant_id { get; set; }
        public int reminder_status { get; set; }
        public string reminder_desc { get; set; }
        public string reminder_title { get; set; }
        public Nullable<System.DateTime> reminder_date { get; set; }

        public string FormattedDate
        {
            get
            {
                return reminder_date?.ToString("d MMMM yyyy");
            }
        }

        public string CombinedNames
        {
            get
            {
                if (!string.IsNullOrEmpty(landlord?.landlord_name) && !string.IsNullOrEmpty(tenant?.tenant_name))
                {
                    return $"{landlord.landlord_name} - {tenant.tenant_name}";
                }
                else if (!string.IsNullOrEmpty(landlord?.landlord_name))
                {
                    return landlord.landlord_name;
                }
                else if (!string.IsNullOrEmpty(tenant?.tenant_name))
                {
                    return tenant.tenant_name;
                }
                else
                {
                    return string.Empty;
                }
            }
        }


        public virtual landlord landlord { get; set; }
        public virtual tenant tenant { get; set; }
    }
}
