//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roomRental.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_roomrentalEntities : DbContext
    {
        public db_roomrentalEntities()
            : base("name=db_roomrentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cleanerAtt> cleanerAtts { get; set; }
        public virtual DbSet<finance> finances { get; set; }
        public virtual DbSet<floor> floors { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<Investor> Investors { get; set; }
        public virtual DbSet<landlord> landlords { get; set; }
        public virtual DbSet<profit> profits { get; set; }
        public virtual DbSet<reminder> reminders { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tenant> tenants { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
