//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roomRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int Inventory_id { get; set; }
        public string floor_id { get; set; }
        public string inventory_name { get; set; }
        public int inventory_count { get; set; }
    
        public virtual floor floor { get; set; }
    }
}
