//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roomRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenant
    {
        public int tenant_id { get; set; }
        public int tenant_ic { get; set; }
        public string tenant_uploadIC { get; set; }
        public string tenant_name { get; set; }
        public int tenant_contract { get; set; }
        public string tenant_phoneNo { get; set; }
        public string tenant_emergencyNo { get; set; }
        public int tenant_noSiri { get; set; }
        public System.DateTime tenant_inDate { get; set; }
        public System.DateTime tenant_outDate { get; set; }
        public Nullable<System.DateTime> tenant_outTime { get; set; }
        public double tenant_outstanding { get; set; }
        public string tenant_paymentStatus { get; set; }
        public string room_id { get; set; }
    
        public virtual room room { get; set; }
    }
}
